#ifndef AZUSADESIGNERSDK_GLOBAL_H
#define AZUSADESIGNERSDK_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(AZUSADESIGNERSDK_LIBRARY)
#  define AZUSADESIGNERSDKSHARED_EXPORT Q_DECL_EXPORT
#else
#  define AZUSADESIGNERSDKSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // AZUSADESIGNERSDK_GLOBAL_H
